controller_names:
  - rizon_arm_controller
  - flexiv_gripper_node

rizon_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7

flexiv_gripper_node:
  action_ns: gripper_action
  type: GripperCommand
  default: true
  joints:
    - finger_width_joint
